_core:
  default_config_hash: bBsKNU9uuzzS7zaKZhHpof7W8sOAuKBZJDF5Eh76BTs
langcode: es
name: 'PWA Testing'
short_name: 'PWA Testing'
app_id: pwa-testing.com
description: ''
start_url: /
scope: /
lang: ''
dir: auto
orientation: any
categories:
  - ''
theme_color: '#000000'
background_color: '#000000'
display: fullscreen
cross_origin: false
image_fid: 1
image_small_fid: 4
image_very_small_fid: 5
manifest_path_mode: all_except_listed
manifest_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*"
